#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint js and vue files
npx --no-install lint-staged

# Lint only staged ruby files (excluding deleted files)
git diff --diff-filter=ACM --name-only --cached | grep '\.rb$' | xargs bundle exec rubocop --force-exclusion -a

# Stage rubocop changes to files (excluding deleted files)
git diff --diff-filter=ACM --name-only --cached | xargs git add
